create extension if not exists "pgcrypto";

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  lat double precision not null,
  lng double precision not null,
  type text not null,
  photo_url text,
  angry_count integer not null default 0,
  repaired boolean not null default false,
  repaired_at timestamptz,
  repair_rating_avg numeric(3, 2) not null default 0,
  repair_rating_count integer not null default 0
);

create index if not exists reports_created_at_idx on public.reports (created_at desc);

create table if not exists public.report_angry_votes (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.reports (id) on delete cascade,
  fingerprint text not null,
  created_at timestamptz not null default now(),
  unique (report_id, fingerprint)
);

create table if not exists public.report_repair_ratings (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.reports (id) on delete cascade,
  fingerprint text not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  unique (report_id, fingerprint)
);

create table if not exists public.rate_limits (
  key text primary key,
  fingerprint text not null,
  route text not null,
  window_start timestamptz not null,
  count integer not null default 0
);
