create extension if not exists "pgcrypto";

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  lat double precision not null,
  lng double precision not null,
  type text not null,
  category text not null default 'Baches',
  subcategory text not null default 'Grieta',
  status text not null default 'Visible',
  photo_url text,
  angry_count integer not null default 0,
  repaired boolean not null default false,
  repaired_at timestamptz,
  repair_rating_avg numeric(3, 2) not null default 0,
  repair_rating_count integer not null default 0,
  user_id uuid,
  reporter_fingerprint text
);

alter table public.reports add column if not exists category text;
alter table public.reports add column if not exists subcategory text;
alter table public.reports add column if not exists status text;
alter table public.reports add column if not exists user_id uuid;
alter table public.reports add column if not exists reporter_fingerprint text;

update public.reports
set
  category = coalesce(category, 'Baches'),
  subcategory = coalesce(subcategory, type, 'Grieta'),
  status = coalesce(
    status,
    case
      when repaired = true then 'Reparado'
      else 'Visible'
    end
  )
where category is null
  or subcategory is null
  or status is null;

alter table public.reports
  alter column category set default 'Baches',
  alter column subcategory set default 'Grieta',
  alter column status set default 'Visible';

alter table public.reports
  alter column category set not null,
  alter column subcategory set not null,
  alter column status set not null;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  email text not null,
  role text not null default 'citizen',
  avatar_key text not null default 'bart.svg',
  password_hash text not null,
  created_at timestamptz not null default now(),
  unique (username),
  unique (email)
);

alter table public.users add column if not exists role text;
alter table public.users add column if not exists avatar_key text;
update public.users set role = 'citizen' where role is null;
update public.users set avatar_key = 'bart.svg' where avatar_key is null;
alter table public.users alter column role set default 'citizen';
alter table public.users alter column role set not null;
alter table public.users alter column avatar_key set default 'bart.svg';
alter table public.users alter column avatar_key set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_role_check'
  ) then
    alter table public.users
      add constraint users_role_check
      check (role in ('citizen', 'admin'));
  end if;
end;
$$;

create table if not exists public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'reports_user_id_fkey'
  ) then
    alter table public.reports
      add constraint reports_user_id_fkey
      foreign key (user_id) references public.users(id) on delete set null;
  end if;
end;
$$;

create index if not exists reports_created_at_idx on public.reports (created_at desc);
create index if not exists reports_user_id_idx on public.reports (user_id);
create index if not exists reports_reporter_fingerprint_idx on public.reports (reporter_fingerprint);
create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_category_idx on public.reports (category);
create index if not exists users_email_idx on public.users (email);
create index if not exists users_username_idx on public.users (username);
create index if not exists user_sessions_user_id_idx on public.user_sessions (user_id);
create index if not exists user_sessions_expires_at_idx on public.user_sessions (expires_at);

create table if not exists public.report_angry_votes (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.reports (id) on delete cascade,
  fingerprint text not null,
  created_at timestamptz not null default now(),
  unique (report_id, fingerprint)
);

create table if not exists public.report_repair_ratings (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.reports (id) on delete cascade,
  fingerprint text not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  unique (report_id, fingerprint)
);

create table if not exists public.rate_limits (
  key text primary key,
  fingerprint text not null,
  route text not null,
  window_start timestamptz not null,
  count integer not null default 0
);
